# this_file: src_docs/mkdocs.yml

site_name: "Claif Knollm - LLM Provider Catalog"
site_description: "Comprehensive catalog of LLM providers, models, and Python libraries with intelligent routing capabilities"
site_author: "Adam Twardoch"
site_url: "https://twardoch.github.io/claif_knollm/"

# Build configuration
docs_dir: "md"
site_dir: "../docs"

# Repository information
repo_name: "twardoch/claif_knollm"
repo_url: "https://github.com/twardoch/claif_knollm"
edit_uri: "edit/main/src_docs/md/"

# Copyright information
copyright: "Copyright © 2025 Adam Twardoch. Licensed under MIT License."

# Theme configuration
theme:
  name: "material"
  
  # Color scheme
  palette:
    # Light mode
    - scheme: "default"
      primary: "blue"
      accent: "amber"
      toggle:
        icon: "material/brightness-7"
        name: "Switch to dark mode"
    
    # Dark mode  
    - scheme: "slate"
      primary: "blue"
      accent: "amber"
      toggle:
        icon: "material/brightness-4"
        name: "Switch to light mode"
  
  # Typography
  font:
    text: "Roboto"
    code: "Roboto Mono"
  
  # Logo and favicon
  icon:
    logo: "material/brain"
    repo: "fontawesome/brands/github"
  favicon: "assets/images/favicon.ico"
  
  # Features
  features:
    # Navigation
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.sections"
    - "navigation.expand"
    - "navigation.path"
    - "navigation.indexes"
    - "navigation.top"
    - "navigation.footer"
    
    # Search
    - "search.highlight"
    - "search.share"
    - "search.suggest"
    
    # Header
    - "header.autohide"
    
    # Content
    - "content.code.copy"
    - "content.code.annotate"
    - "content.tabs.link"
    - "content.tooltips"
    
    # Table of contents
    - "toc.follow"
    - "toc.integrate"

# Navigation structure
nav:
  - "Home": "index.md"
  
  - "Getting Started":
    - "getting-started/index.md"
    - "Installation": "getting-started/installation.md"
    - "Quick Start": "getting-started/quickstart.md"
    - "Configuration": "getting-started/configuration.md"
  
  - "Providers":
    - "providers/index.md"
    - "Provider Catalog": "providers/catalog.md"
    - "Provider Comparison": "providers/comparison.md"
    - "Integration Guide": "providers/integration.md"
  
  - "Models":
    - "models/index.md"
    - "Model Database": "models/database.md"
    - "Search & Filtering": "models/search.md"
    - "Model Capabilities": "models/capabilities.md"
    - "Pricing & Costs": "models/pricing.md"
  
  - "Python Libraries":
    - "libraries/index.md"
    - "Library Comparison": "libraries/comparison.md"
    - "Recommendations": "libraries/recommendations.md"
    - "Integration Examples": "libraries/integration.md"
  
  - "API Reference":
    - "api/index.md"
    - "Client API": "api/client.md"
    - "Registry API": "api/registry.md"
    - "Routing API": "api/routing.md"
    - "Utilities": "api/utilities.md"
  
  - "Guides":
    - "guides/index.md"
    - "Multi-Provider Strategies": "guides/multi-provider.md"
    - "Cost Optimization": "guides/optimization.md"
    - "Monitoring & Analytics": "guides/monitoring.md"
    - "Best Practices": "guides/best-practices.md"
  
  - "Examples":
    - "examples/index.md"
    - "Basic Usage": "examples/basic-usage.md"
    - "Advanced Use Cases": "examples/advanced.md"
    - "Framework Integration": "examples/integration.md"
    - "Benchmarking": "examples/benchmarking.md"
  
  - "Reference":
    - "reference/index.md"
    - "CLI Commands": "reference/cli.md"
    - "Configuration": "reference/configuration.md"
    - "Troubleshooting": "reference/troubleshooting.md"

# Plugins
plugins:
  # Built-in search
  - search:
      lang: 
        - "en"
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      
  # Git information
  - git-revision-date-localized:
      enable_creation_date: true
      type: "datetime"
      fallback_to_build_date: true
      
  # API documentation generation
  - mkdocstrings:
      handlers:
        python:
          paths: ["../src"]
          options:
            docstring_style: "google"
            docstring_section_style: "table"
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
  
  # Note: pymdownx.superfences is listed in markdown_extensions, not as a plugin

# Markdown extensions
markdown_extensions:
  # Python-Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: "On this page"
  
  # Python-Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: "all"
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: "twardoch"
      repo: "claif_knollm"
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript (optional files - will be created later)
# extra_css:
#   - "stylesheets/extra.css"
#   - "stylesheets/model-browser.css"

# extra_javascript:
#   - "javascripts/extra.js"
#   - "javascripts/model-browser.js"

# Analytics and external integrations
extra:
  # Social links
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/twardoch/claif_knollm"
      name: "GitHub Repository"
    - icon: "fontawesome/brands/python"
      link: "https://pypi.org/project/claif-knollm/"
      name: "PyPI Package"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/adamtwar"
      name: "Twitter"
  
  # Analytics
  analytics:
    provider: "google"
    property: "G-XXXXXXXXXX"  # Replace with actual GA4 tracking ID
    feedback:
      title: "Was this page helpful?"
      ratings:
        - icon: "material/emoticon-happy-outline"
          name: "This page was helpful"
          data: "1"
          note: "Thanks for your feedback!"
        - icon: "material/emoticon-sad-outline"
          name: "This page could be improved"
          data: "0"
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/twardoch/claif_knollm/issues/new/?title=[Docs]+{title}+-+{url}" target="_blank" rel="noopener">opening an issue</a>.
  
  # Version information
  version:
    provider: "mike"
    default: "stable"
  
  # Generator attribution
  generator: false

# Watch for changes in these directories during development
watch:
  - "../src/claif_knollm"
  - "md"